### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by YuriBrunetto**
add the usage of the files

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Looks good. Let's bring the images into the repo, you can make a `.github` directory and put them there

**Comment by YuriBrunetto** [comment]
i'm sorry but I didnt understand what you mean :ll can you explain?

**Comment by shakeelmohamed** [comment]
:smile:  Instead of linking to the images on imgur, we can upload them to the repo. I'd prefer to keep the images in the repo, and a good place for them is in a `.github` directory. The `.github` directory doesn't currently exist

**Comment by YuriBrunetto** [comment]
ahh, okay! I'll do it tonight

**Comment by YuriBrunetto** [comment]
done! :smile:

**Comment by shakeelmohamed** [comment]
Thanks!

**Pull request merged**
